language: node_js
node_js:
- '9'
install: true
script: true
deploy:
  provider: firebase
  token:
    secure: "LTafwDnIgyE7crutD8SB/Me3qELggqIHRBhCS+gh6qXJKnz9QLs24WQ5T5KPi7YcgkNaKmTxo10mwVId8md9Gi9QisSiNl1UjibfpZAlmgHP9zGWPW/qbsBjm+W2eZmXjEtWLXAtRSOrKFJ+UAQa4aPifbN7xOmMAaNVI6Lq5D+1ncDoa9+CrCnSe4gt64NPgNayQvemeaHidfdEYyJ6B/4rILnLPWTqIvxV0BFhSoGjM/2RMRAX4psvwTHYmtFteycqe4R82v9//2fhAEHlKnlDyqA7quZ0YuStvyBhoWGbrIF9652NR/MyHX+zADeYg3xK45n+UBTZ8bE6/fttbETPRBafZpR0tWpw43KVX/ZAdMFIztNwrhJ2g6UID07nrFBoV/cJqA0P3RTARHw9FPmKAqpsSMOvM3PaI9dB09lmhey4rFU0SaLtv6jIKM0jIt/vTn1wLdi3NaKAkpKmEZl8EThMSHRikNQM32+iCsuK9Yy0e2cHSu4TYkrWub0zTGBF5fHm1a+pzlJdN3R9QvaIDruWnCed3GwG/6Y+Z0xpLGf06Lf9IvbY675re3hq98Ya5SZiRjw18wH3oYL5jGgyS/k+8lgwwVgOkNTjw9CIr6abXOUWpBie1MefIOfmH/2o/rVsH6q+F7V+RgfyRzzWarAcaeCaADyBfQFgTak="

